AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Resume unique visitor counter API

Globals:
  Function:
    Runtime: python3.12
    Timeout: 5
    Handler: app.lambda_handler

Parameters:
  TableName:
    Type: String
    Default: visitor_counter

Resources:
  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

  VisitorApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Environment:
        Variables:
          TABLE_NAME: !Ref VisitorCounterTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !GetAtt VisitorCounterTable.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /count
            Method: post
            RestApiId: !Ref VisitorApi

Outputs:
  VisitorApiUrl:
    Description: "API endpoint for visitor counter"
    Value: !Sub "https://${VisitorApi}.execute-api.${AWS::Region}.amazonaws.com/prod/count"
